stages:
  - start
  - build
  #- test
  - release
  
start:
  stage: start
  when: manual
  allow_failure: false
  script:
    - echo "Starting Jupyter jobs"
  only:
    - schedules
    - web

build-sparkmonitor-js:
  stage: build
  script:
    - echo "Building Sparkmonitor JS"
    - cd SparkMonitor
    - yarn config set cache-folder .yarn
    - yarn install
    - yarn run webpack
  cache:
    untracked: true
    key: "$CI_PROJECT_ID.js"
    paths:
      - SparkMonitor/node_modules/
      - SparkMonitor/.yarn
  artifacts:
    paths:
      - SparkMonitor/sparkmonitor/
  only:
    - schedules
    - web

build-sparkmonitor-scala:
  stage: build
  script:
    - echo "Building Sparkmonitor Scala"
    - cd SparkMonitor/scalalistener/
    - sbt package
  cache:
    untracked: true
    key: "$CI_PROJECT_ID.scala"
    paths:
      - SparkMonitor/scalalistener/target/
  artifacts:
    paths:
      - SparkMonitor/sparkmonitor/
  only:
    - schedules
    - web

release-extra_libs:
  stage: release
  script:
    - echo "Compiling artifacts for extra_libs"
  artifacts:
    name: "extra_libs"
    paths:
      - SparkMonitor/sparkmonitor/
      - Swan*
      - scripts
      - templates
    expire_in: 3 days
  only:
    - schedules
    - web
