stages:
  - build
  - release

build-release:
  stage: build
  image: gitlab-registry.cern.ch/swan/docker-images/builder
  script:
    - echo "Building Extensions"
    - ls -d ./*/ | xargs -n1 sh -c 'if [ -e $0Makefile ]; then echo "Building $0" ; cd $0 ; make ; fi'
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - ./
  tags:
    - docker

release-commit:
  stage: release
  script:
    - echo "Building artifact for $CI_PIPELINE_ID"
    - rm -rf ./*/js ./*/node_modules ./*/Makefile ./*/package.json ./*/webpack.config.js ./*/yarn.lock ./*/conf.json ./*/scalalistener .git*
  artifacts:
    name: $CI_PIPELINE_ID
    paths:
      - ./*
    expire_in: 1 days

release-version:
  stage: release
  script:
    - echo "Releasing $CI_COMMIT_TAG"
    - rm -rf ./*/js ./*/node_modules ./*/Makefile ./*/package.json ./*/webpack.config.js ./*/yarn.lock ./*/conf.json ./*/scalalistener .git*
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - ./
  artifacts:
    name: $CI_COMMIT_TAG
    paths:
      - ./*
    expire_in: 48 weeks
  only: 
      - /^v.*$/

release-daily:
  stage: release
  script:
    - echo "Temporary release"
    - rm -rf ./*/js ./*/node_modules ./*/Makefile ./*/package.json ./*/webpack.config.js ./*/yarn.lock ./*/conf.json ./*/scalalistener .git*
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - ./
  artifacts:
    name: "daily"
    paths:
      - ./*
    expire_in: 3 days
  only:
    - qa
    - web
    - schedules
